// <auto-generated />
using System;
using DataAccessLayer.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(RestaurantDbContext))]
    [Migration("20231113030821_Initialize")]
    partial class Initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EntityLayer.Entities.About", b =>
                {
                    b.Property<int>("About_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("About_ID"), 1L, 1);

                    b.Property<string>("About_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("About_Image_Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("About_Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("About_ID");

                    b.ToTable("Abouts");
                });

            modelBuilder.Entity("EntityLayer.Entities.Booking", b =>
                {
                    b.Property<int>("Booking_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Booking_ID"), 1L, 1);

                    b.Property<DateTime>("Booking_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Booking_Mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Booking_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Booking_Person_Count")
                        .HasColumnType("int");

                    b.Property<string>("Booking_Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Booking_ID");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("EntityLayer.Entities.Category", b =>
                {
                    b.Property<int>("Category_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Category_ID"), 1L, 1);

                    b.Property<string>("Category_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Category_Status")
                        .HasColumnType("bit");

                    b.HasKey("Category_ID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("EntityLayer.Entities.Contact", b =>
                {
                    b.Property<int>("Contact_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Contact_ID"), 1L, 1);

                    b.Property<string>("Contact_Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact_Mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact_Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Contact_ID");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("EntityLayer.Entities.Discount", b =>
                {
                    b.Property<int>("Discount_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Discount_ID"), 1L, 1);

                    b.Property<string>("Discount_Amount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discount_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discount_Image_Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discount_Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Discount_ID");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("EntityLayer.Entities.Feature", b =>
                {
                    b.Property<int>("Feature_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Feature_ID"), 1L, 1);

                    b.Property<string>("Feature_Description_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Feature_Description_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Feature_Description_3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Feature_Image_Url_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Feature_Image_Url_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Feature_Image_Url_3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Feature_Title_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Feature_Title_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Feature_Title_3")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Feature_ID");

                    b.ToTable("Features");
                });

            modelBuilder.Entity("EntityLayer.Entities.Product", b =>
                {
                    b.Property<int>("Product_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Product_ID"), 1L, 1);

                    b.Property<string>("Product_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Product_Image_Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Product_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Product_Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Product_Status")
                        .HasColumnType("bit");

                    b.HasKey("Product_ID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("EntityLayer.Entities.SocialMedia", b =>
                {
                    b.Property<int>("Social_Media_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Social_Media_ID"), 1L, 1);

                    b.Property<string>("Social_Media_Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Social_Media_Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Social_Media_Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Social_Media_ID");

                    b.ToTable("SocialMedias");
                });

            modelBuilder.Entity("EntityLayer.Entities.Testimonial", b =>
                {
                    b.Property<int>("Testimonial_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Testimonial_ID"), 1L, 1);

                    b.Property<string>("Testimonial_Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Testimonial_Image_Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Testimonial_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Testimonial_Status")
                        .HasColumnType("bit");

                    b.Property<string>("Testimonial_Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Testimonial_ID");

                    b.ToTable("Testimonials");
                });
#pragma warning restore 612, 618
        }
    }
}
